name: CI — Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.1.0

      - name: Run flake8
        run: |
          # Lint the main script and any supporting .py files
          flake8 --max-line-length=120 --extend-ignore=E203,W503 .

      - name: Upload lint results (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: .
